"""headache

Revision ID: 410cb04e8123
Revises: 
Create Date: 2020-04-27 11:28:41.582217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410cb04e8123'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('post_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'post_id')
    # ### end Alembic commands ###
