"""passwordnul

Revision ID: 991a90f0ca1c
Revises: b868b16cc769
Create Date: 2020-04-18 21:49:34.763951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991a90f0ca1c'
down_revision = 'b868b16cc769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_has',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_has',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
